site_name: e2 docs
nav:
    - 主页: index.md
    - 关于: about.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top